title: "Matthew Wang"
author: "Matthew Wang"
description: "Last Updated: July 26, 2023"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "Home"}
  - {file: "projects.html", title: "Projects"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:mwang0401@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/hextechagon/"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/mattwang8/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

collections:
  projects:
    output: true
  experiences:
    output: true

plugins:
 - jekyll-feed
